### ISSUE TITLE
chrstphrknwtn's screensavers no longer work

### ISSUE THREAD

**Issue by ivan-antonyuck** [agarrharr/awesome-macos-screensavers#65]
It seems that @chrstphrknwtn 's certificate has expired, so either screensavers need to be rebuilt or removed from this list.

**Comment by agarrharr** [comment]
Which screensavers?

**Comment by chrstphrknwtn** [comment]
@ivan-antonyuck Thanks for the heads-up. Though I would like to point out that GitHub is primarily for sharing code, not only prebuilt working software. So removing from them all from this list because the binaries don't work seems a bit extreme.

Nevertheless, you make a good point. I'll rebuild the `.saver` files update the download links so the screensavers work as expected.

**Comment by chrstphrknwtn** [comment]
It appears that macOS Monterey (and probably Catalina also) does the notarised check thing when loading it in the system preference panel, rather than when the user opens the `.saver` file. So 'not working' appears to be consistent for all screensavers in this list.

Creating a notarised `DMG` for download seems to be workaround, as briefly described on this screensaver repo: [Epigraver](https://github.com/rbeeger/epigraver#installation)

If I find time to fix mine using this [build script](https://github.com/rbeeger/epigraver/blob/main/buildRelease.sh) then I'll post an update here.

**Comment by ivan-antonyuck** [comment]
@chrstphrknwtn  Thanks! Sorry for noting this here, the screensaver repos seemed abandoned to me.
